# Site settings
title: Bootstragram Web Commons
description: > # this means to ignore newlines until "baseurl:"
  A great collection of web commons. By Bootstragram.
baseurl: "/bootstragram-web-commons" # the subpath of your site, e.g. /blog
url: "http://webcommons.bootstragram.com" # the base hostname & protocol for your site
twitter_username: bootstragram
facebook_pagename: bootstragram
destination: dist
github_url: "https://github.com/Bootstragram"

# Build settings
markdown: kramdown

permalink:  /:title.html
exclude: [ 'bower_components', 'node_modules', 'Gruntfile.js', 'bower.json' ]

gems:
 - jekyll-sitemap
 - jekyll-coffeescript
