# Site settings
title: Bootstragram Web Commons
description: > # this means to ignore newlines until "baseurl:"
  A great collection of web commons. By Bootstragram.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://webcommons.bootstragram.com" # the base hostname & protocol for your site
twitter_username: bootstragram
facebook_pagename: bootstragram
destination: ~/Developer/build/bootstragram-web-commons-gh-pages
github_url: "https://github.com/Bootstragram"

# Build settings
markdown: kramdown

permalink:  /:title.html
exclude: [ 'bower_components', 'node_modules', 'bower.json', 'Gemfile', 'Gemfile.lock', 'Gruntfile.js', 'package.json', 'README.md', 'config', 'Rakefile', 'CHANGELOG.md', '.git', 'dist', 'jsdoc-README.md', 'jsdoc.json']

gems:
  - jekyll-sitemap
  - jekyll-coffeescript
